### ISSUE TITLE
Data Cleaning: Many -> specific

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/resources_api#22]
In the provided data we have many instances where the language is listed as `multiple` (and possibly other vague values.

Acceptance criteria.

1. resources.yaml will no longer have any of these vague languages
2. any category you identify as vague will be added to a blacklist in the file db_setup script to prevent this happening in the future.

**Comment by aaron-suarez** [comment]
@wimo7083 Do you think these 3 data cleaning issues will be easier or harder to address once we go live and stop relying on the resources.yml file? If it will be easier (or the same), I'm all about going live as soon as we get the currently outstanding PRs merged. If it will be harder, we may have to prioritize these issues and figure out what we can't live without so to speak before we go live.

I defer to your opinion on it because you've done a lot of data cleaning compared to me in your professional work.

If you want to take this conversation to slack and possibly get other opinions from the OC data community, let's do that. Just let me know how you want to proceed.

**Comment by aaron-suarez** [comment]
I think that when we get the frontend set up, we can go ahead and crowdsource this by asking people to update resources they like that say "multiple" for the language with the languages they actually have. Unpopular resources that no one uses may stay unfound for a long time, but I suspect that the more popular ones will be updated quickly enough. I'll leave this issue open for now, but we're past the point of working with the resources.yml file and it's time to start focusing on data cleaning in the prod DB itself

**Comment by aaron-suarez** [comment]
This past weekend I went through the database and changed all of the "multiple" to their respective multiple languages. It took a very long time. Anyway, I think that this issue is worth closing now. The resources.yml still has "multiple" in it, but the production DB does not and that's good enough for me.
