### ISSUE TITLE
Data Cleaning: Consolidate categories

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/resources_api#23]
Some categories have very limited number of resources: 1-3 resources in a single category. This change is to consolidate these categories into a more fitting one. 

Acceptance criteria:
1. write CLI Command that processes `resources.yaml` and identifies these low usage categories and the resource that uses them
2. Where possible find a better broad category. In the future we might need sub-categories.

**Comment by CryptoJones** [comment]
I'll take this.

**Comment by aaron-suarez** [comment]
This particular command has proven helpful:
```bash
grep "category:" resources.yml | sort -n | uniq -c
```
This will print out the number of resources in each category next to the category name.

**Comment by aaron-suarez** [comment]
I very much hope that Algolia has solved this problem a little bit for us since the frontend will be based more on the search endpoint rather than displaying a bunch of categories. People can categorize it however they want, and if someone wants to browse a category that contains only a single resource, that's ok by me. We'll make adjustments as we learn how this ends up being used.

For now, I'll close it out and we can clean the data in the prod db if necessary
