### ISSUE TITLE
When updating a resource, logs should print JSON 

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#356]
Currently, when you update a resource, the logs print out the Python object of what was sent (a dictionary, a list, etc). Instead, the logs should contain the JSON form of this data so that if we need to restore it, we can just copy and paste it into the request and press "send" without having to process any additional data.

**Comment by evmende** [comment]
logger.info(f"Updating resource. Old data: {json.dumps(resource.serialize)}")

Not sure if this is doing what you need it to. My understanding is the json.dumps(resource.serialize) converts the resource.serialize object to json, then that is formatted by the f-string and passed into logger.info

Question 1: Do I need to keep the f-string since I formatted the data to json?
Question 2: Is the above code doing what I think it is, or do I need to do this:

resource.serialize_json = json.dumps(resource.serialize)
logger.info(f"Updating resource. Old data: {resource.serialize_json}")

**Comment by aaron-suarez** [comment]
The code you provided is exactly what I was trying to guide you toward. I'm glad you made it there without me having to give you the answer :smile:

If you want to ditch the f-string, it will look like this:
```python
logger.info("Updating resource. Old data:" + json.dumps(resource.serialize))
```

I'll leave it up to you to decide which looks cleaner. Whatever you do, go ahead and make the request and see what it looks like in the logs to make sure it looks like you expect it to.

If you need help doing that, just let me know and I'll show you how

**Comment by evmende** [comment]
FRICKEN PUMPED! Glad I got the answer. I was beginning to wonder....

Yea I'm not sure I'm running this right with 

`make all`

Then going to http://localhost:5000/api/v1/apikey

It doesn't ask for my credentials and I get this error:

`apiVersion"1.0"errorsmethod-not-allowedmessage"

This method is not allowed."status"

Method Not Allowed"status_code405`

I'm kinda lost on what should have happened.

Unless you just want me to make the request?

**Comment by aaron-suarez** [comment]
I'm not sure what you mean by "then going to..."

What you need to do to get your API key is make a POST request to the `/apikey` endpoint, with a JSON body containing your OC username and password (there's an example in the README. So you can't "go to it" with your browser, you need to use a tool like Postman or curl to send a POST with the right data. GET requests aren't allowed to that endpoint, which is why it returns a "405 method not allowed"
