### ISSUE TITLE
Change "paid" to "free"

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#369]
Resources currently have an attribute of "paid" which is either true or false. However, it's not entirely clear what this means. Instead, the attribute should be "free". This will require a switch of all of the current data, because it means the opposite (for example, right now, freecodecamp is in there as "paid: false" but it will need to be "free: true"). I don't have a great idea for exactly how we'll clean the data so I'm open to suggestions from whoever wants to work on it; we can come up with something together!

**Comment by aaron-suarez** [comment]
This will require docs changes as well, so don't forget to edit the swagger file!

**Comment by Kandeel4411** [comment]
Helloo! I think I could work on this if its still up

**Comment by techytushar** [comment]
Hey @aaron-suarez since there hasn't been any update for few days, I would like to take this up. According to me the steps involved in solving this would be:

1. Update the `paid` field in `Resource` in `models.py`
2. Run a SQL Update query on the existing database which will just reverse the boolean values ([https://stackoverflow.com/questions/15183012/update-a-boolean-to-its-opposite-in-sql-without-using-a-select](https://stackoverflow.com/questions/15183012/update-a-boolean-to-its-opposite-in-sql-without-using-a-select))
3. Update the docs

**Comment by Kandeel4411** [comment]
Hey @techytushar, sorry if it wasnt clear - the link in the PR wasnt working. This issue is mostly already done, we are just waiting for input from the frontend people to co-ordinate the change
