### ISSUE TITLE
Dockerfile should not be root

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#383]
Right now, the Dockerfile runs as root because that's the default. Instead, there should be a non-root user that the uwsgi process runs as.

**Comment by Kandeel4411** [comment]
I think I could work on this - Also I had a minor side question about the `make setup` in Makefile, Is there a reason we are mostly using `docker-compose run` instead of `docker-compose exec` ?
For example, the following happens:
```makefile
.PHONY: bg
bg:
	${DOCKER_COMPOSE} up --build -d   # A new db and resource container created and running

#--------------------Some other stuff------------------------------

.PHONY: setup
setup: bg
	${DOCKER_COMPOSE} run ${RESOURCES_CONTAINER} ${FLASK}  # Another new oneshot container created
	${DOCKER_COMPOSE} run ${RESOURCES_CONTAINER} ${FLASK} db-migrate create-tables  # Again
	${DOCKER_COMPOSE} run ${RESOURCES_CONTAINER} ${FLASK} db stamp head # Again
	${DOCKER_COMPOSE} run ${RESOURCES_CONTAINER} ${FLASK} db-migrate init # Again
````
This leads to multiple uneccessary stopped containers, if we substitute the `run` to `exec`  it would utilize the already up container created by `bg` and would make it faster as well. Though I could be wrong so I'd love to know more!

**Comment by aaron-suarez** [comment]
At the time, I don't think any of us realized that it wasn't using the same container. Feel free to change it to `docker-compose exec` and if I don't see that breaking any functionality, I'll merge. Thanks for pointing that out!
