### ISSUE TITLE
Check for expired URL

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/resources_api#83]
It would be really cool to have a way to check all resource urls programatically for a bad link.

Some sites will not allow you to do HEAD or GET requests, and in those cases we can blacklist (or whitelist the opposite).

In the future we can modify the table for the database on resources to include a whitelist or blacklist flag. 

Also in the future we can determine when this is run, but for now we can hook it into unit tests, either in a sub-module that doesn't get run all the time, or in the main tests that get run all the time.

**Comment by wimo7083** [comment]
an example of a MVP for this:

```python
from requests import get

def test_urls(db, session):
    resources = db.session.query(Resources).all()
    for resource in resources:
        r = get(resource.url)
        assert r.status < 400
```
Another way would be to get all the results, and then store the ones that are good status codes, and then once at the end check if they are all good. It's not best practice to parametrize in a for loop, but I'm not sure how to do it when we have a fixture on the database. Maybe use the raw yaml data?

**Comment by Kshitij09** [comment]
Hello, I'd like to work on this. Just for clarification, I should first work on checking for bad links right ? Or should I implement the blacklist database as well ?

**Comment by aaron-suarez** [comment]
@Kshitij09 I'm a big fan of starting small and iterating on that. Why don't we start with checking for the bad links and then once we get that merged, we can open a separate issue for the blacklist? You can feel free to pick up the blacklist issue as well, but I would rather not let a single PR get too big.

I disagree with putting this in the unit tests though, mainly because of CI concerns. Besides, it's more important for the production environment and all of the tests should have passed by the time it gets to prod. So I'd like to see this implemented as a click command instead. It can print out the IDs and URLs that are bad, so the administrator can go in and perform a SQL query to clean them up after reviewing them. I'm open to other ideas, but this doesn't feel like a unit test to me.

**Comment by Kshitij09** [comment]
I think the same way. It's good idea to start with checking for bad links and then extend the same. I'm looking forward to get this done as soon as possible :)
